trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:    
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Registry Service COnnection'
        repository: 'rahulk86/sampleapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Proviion
  displayName: 'Creating terraform on azure'
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: 'Provision container instance'
    pool: 
      name: Default
    variables: 
    - group: SampleApiVariable
    steps:
     - script: |
        set -e
        
        terraform init -input=false
        terraform apply -input=false -auto-approve
       name: 'RunTerraform'
       displayName: 'Running Terraform'
       env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_imagebuild: $(tag)
    
